### ISSUE TITLE
Have a fallback subsystem, points amount & scenario is none is found (vanilla, random points between a range and Regular Deathmatch)

### ISSUE THREAD

**Issue by cbonaudo** [cbonaudo/mini-game-selector#22]

**Comment by rbonaudo** [comment]
What should we do in case of a Game System / Subsystem with no scenario ?
For example, if we draw a One-Off Game / WarRacing, there would be no valid scenario for that.

**Comment by cbonaudo** [comment]
Have a regular one, Just the game, with no spécification. Or a fallback, like vanilla, desc: Just vanilla rules
